-- Run this in Snowsight on QIAPQJI-YM84445 as JBILEKTRIAL (ACCOUNTADMIN)

-- Key-pair service user for CI tests
CREATE USER JBILEKTRIAL_CI_KP
  TYPE = SERVICE
  RSA_PUBLIC_KEY = 'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3oV2WmxI94TAD6GjH3dUVDyjn8y4HrtHVXWZozhPW73S8MGd9UlbbvWl+TYAjs+xm6lf7k5auCLUHRpN0lVH+nxXNwhtjzLrzdtMeMKpKN31b7tXkC/Qik5sDrTTOLcCF9w8+TCsAiS/QzDNHU/xL/86Ys9l7PqpM9ir3DKMjy9VnTK6SF9a/N4I/57escWWB8sBgMaqgxAp/hR+x7r0HLZAMkj3neiUxHDPMd50vYjpGJhzYvxTmZFd3HupgkToM6l/tyT4T/HvaekE445AkJnnRwTHLnFQFeX0fKA6Vm+Z0GoSWVKq9O506TY4Nke/zlUA03E7Ug1g21w+xChHYwIDAQAB'
  DEFAULT_ROLE = SYSADMIN;
GRANT ROLE SYSADMIN TO USER JBILEKTRIAL_CI_KP;

-- OIDC service user for CI tests
CREATE USER JBILEKTRIAL_CI_OIDC
  TYPE = SERVICE
  WORKLOAD_IDENTITY = (
    TYPE = OIDC
    ISSUER = 'https://token.actions.githubusercontent.com'
    SUBJECT = 'repo:sfc-gh-jbilek/snowflake-actions-test:ref:refs/heads/main'
  )
  DEFAULT_ROLE = SYSADMIN;
GRANT ROLE SYSADMIN TO USER JBILEKTRIAL_CI_OIDC;
