name: "test-01 basic install"
on:
  push:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: snowflakedb/snowflake-actions@feat/modular-install-cli-cortex
      - run: snow --version
