name: "test-02 cli-version input"
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - id: latest
        run: |
          VERSION=$(curl -s https://pypi.org/pypi/snowflake-cli-labs/json | jq -r '.info.version')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - uses: snowflakedb/snowflake-actions@main
        with:
          cli-version: ${{ steps.latest.outputs.version }}
      - run: snow --version | grep "${{ steps.latest.outputs.version }}"
