name: "test-03 custom-github-ref"
on:
  push:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: snowflakedb/snowflake-actions@main
        with:
          custom-github-ref: "main"
      - run: snow --version
